#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
GIT_SHA="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || printf unknown)"
DEV_RUNTIME_ROOT="$("$REPO_ROOT/scripts/dev-runtime-root")"

cat <<EOF
LIFECYCLE_DEV=1
LIFECYCLE_REPO_ROOT=$REPO_ROOT
LIFECYCLE_ROOT=$DEV_RUNTIME_ROOT
LIFECYCLE_RUNTIME_ROOT=$DEV_RUNTIME_ROOT
LIFECYCLE_DEV_STATE_ROOT=$DEV_RUNTIME_ROOT/dev
LIFECYCLE_API_URL=http://127.0.0.1:18787
LIFECYCLE_API_PORT=18787
LIFECYCLE_BRIDGE_URL=http://127.0.0.1:52300
LIFECYCLE_BRIDGE_PORT=52300
LIFECYCLE_GIT_SHA=$GIT_SHA
EOF
