// ⚠️ Auto-generated by routed. Do not edit.
import { Hono } from "hono";
import { routeHandler, wrapMiddleware } from "routedjs/hono";

import middleware0 from "./routes/_middleware.ts";
import middleware1 from "./routes/_authenticated/_middleware.ts";

import route0 from "./routes/auth/device-code.post.route.ts";
import route1 from "./routes/auth/me.get.route.ts";
import route2 from "./routes/auth/token.post.route.ts";
import route3 from "./routes/health.get.route.ts";
import route4 from "./routes/_authenticated/organizations/index.get.route.ts";
import route5 from "./routes/_authenticated/organizations/index.post.route.ts";
import route6 from "./routes/_authenticated/organizations/$orgId.get.route.ts";
import route7 from "./routes/_authenticated/organizations/$orgId/cloud-accounts.get.route.ts";
import route8 from "./routes/_authenticated/organizations/$orgId/cloud-accounts.post.route.ts";
import route9 from "./routes/_authenticated/repos/index.get.route.ts";
import route10 from "./routes/_authenticated/repos/index.post.route.ts";
import route11 from "./routes/_authenticated/repos/$repoId.get.route.ts";
import route12 from "./routes/_authenticated/users/me/environment.get.route.ts";
import route13 from "./routes/_authenticated/users/me/environment.put.route.ts";
import route14 from "./routes/_authenticated/workspaces/index.post.route.ts";
import route15 from "./routes/_authenticated/workspaces/$workspaceId.delete.route.ts";
import route16 from "./routes/_authenticated/workspaces/$workspaceId.get.route.ts";
import route17 from "./routes/_authenticated/workspaces/$workspaceId/exec.post.route.ts";
import route18 from "./routes/_authenticated/workspaces/$workspaceId/pr.post.route.ts";
import route19 from "./routes/_authenticated/workspaces/$workspaceId/pr/merge.post.route.ts";
import route20 from "./routes/_authenticated/workspaces/$workspaceId/shell.get.route.ts";

export const app = new Hono()
  .use("*", wrapMiddleware(middleware0))
  .use("/organizations/*", wrapMiddleware(middleware1))
  .use("/repos/*", wrapMiddleware(middleware1))
  .use("/users/*", wrapMiddleware(middleware1))
  .use("/workspaces/*", wrapMiddleware(middleware1))
  .post("/auth/device-code", routeHandler(route0, "/auth/device-code"))
  .get("/auth/me", routeHandler(route1, "/auth/me"))
  .post("/auth/token", routeHandler(route2, "/auth/token"))
  .get("/health", routeHandler(route3, "/health"))
  .get("/organizations", routeHandler(route4, "/organizations"))
  .post("/organizations", routeHandler(route5, "/organizations"))
  .get("/organizations/:orgId", routeHandler(route6, "/organizations/:orgId"))
  .get("/organizations/:orgId/cloud-accounts", routeHandler(route7, "/organizations/:orgId/cloud-accounts"))
  .post("/organizations/:orgId/cloud-accounts", routeHandler(route8, "/organizations/:orgId/cloud-accounts"))
  .get("/repos", routeHandler(route9, "/repos"))
  .post("/repos", routeHandler(route10, "/repos"))
  .get("/repos/:repoId", routeHandler(route11, "/repos/:repoId"))
  .get("/users/me/environment", routeHandler(route12, "/users/me/environment"))
  .put("/users/me/environment", routeHandler(route13, "/users/me/environment"))
  .post("/workspaces", routeHandler(route14, "/workspaces"))
  .delete("/workspaces/:workspaceId", routeHandler(route15, "/workspaces/:workspaceId"))
  .get("/workspaces/:workspaceId", routeHandler(route16, "/workspaces/:workspaceId"))
  .post("/workspaces/:workspaceId/exec", routeHandler(route17, "/workspaces/:workspaceId/exec"))
  .post("/workspaces/:workspaceId/pr", routeHandler(route18, "/workspaces/:workspaceId/pr"))
  .post("/workspaces/:workspaceId/pr/merge", routeHandler(route19, "/workspaces/:workspaceId/pr/merge"))
  .get("/workspaces/:workspaceId/shell", routeHandler(route20, "/workspaces/:workspaceId/shell"))
;

export type AppType = typeof app;
