// ⚠️ Auto-generated by routed. Do not edit.
import type { StandardSchemaV1 } from "@standard-schema/spec";
import { createClient, type RouteMap, type Client, type ClientOptions } from "routedjs/client";

import type route0 from "./routes/auth/device-code.post.route.ts";
import type route1 from "./routes/auth/me.get.route.ts";
import type route2 from "./routes/auth/token.post.route.ts";
import type route3 from "./routes/health.get.route.ts";
import type route4 from "./routes/_authenticated/organizations/index.get.route.ts";
import type route5 from "./routes/_authenticated/organizations/index.post.route.ts";
import type route6 from "./routes/_authenticated/organizations/$orgId.get.route.ts";
import type route7 from "./routes/_authenticated/organizations/$orgId/cloud-accounts.get.route.ts";
import type route8 from "./routes/_authenticated/organizations/$orgId/cloud-accounts.post.route.ts";
import type route9 from "./routes/_authenticated/repos/index.get.route.ts";
import type route10 from "./routes/_authenticated/repos/index.post.route.ts";
import type route11 from "./routes/_authenticated/repos/$repoId.get.route.ts";
import type route12 from "./routes/_authenticated/users/me/environment.get.route.ts";
import type route13 from "./routes/_authenticated/users/me/environment.put.route.ts";
import type route14 from "./routes/_authenticated/workspaces/index.get.route.ts";
import type route15 from "./routes/_authenticated/workspaces/index.post.route.ts";
import type route16 from "./routes/_authenticated/workspaces/$workspaceId.delete.route.ts";
import type route17 from "./routes/_authenticated/workspaces/$workspaceId.get.route.ts";
import type route18 from "./routes/_authenticated/workspaces/$workspaceId/exec.post.route.ts";
import type route19 from "./routes/_authenticated/workspaces/$workspaceId/pr.post.route.ts";
import type route20 from "./routes/_authenticated/workspaces/$workspaceId/pr/merge.post.route.ts";
import type route21 from "./routes/_authenticated/workspaces/$workspaceId/shell.get.route.ts";

// Extract schema types from route definitions
type InferSchema<T> = T extends { schemas: infer S } ? S : {};
type SchemaType<T> = T extends StandardSchemaV1 ? StandardSchemaV1.InferOutput<T> : undefined;
type PrimarySuccessResponse<T> =
  T extends { 200: infer R } ? R :
  T extends { "200": infer R } ? R :
  T extends { 201: infer R } ? R :
  T extends { "201": infer R } ? R :
  T extends { 202: infer R } ? R :
  T extends { "202": infer R } ? R :
  T extends { 204: infer R } ? R :
  T extends { "204": infer R } ? R :
  undefined;

export type AppRouteMap = {
  "post /auth/device-code": {
    params: SchemaType<InferSchema<typeof route0> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route0> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route0> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route0> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route0> extends { response: infer R } ? R : undefined>;
  };
  "get /auth/me": {
    params: SchemaType<InferSchema<typeof route1> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route1> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route1> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route1> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route1> extends { response: infer R } ? R : undefined>;
  };
  "post /auth/token": {
    params: SchemaType<InferSchema<typeof route2> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route2> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route2> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route2> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route2> extends { response: infer R } ? R : undefined>;
  };
  "get /health": {
    params: SchemaType<InferSchema<typeof route3> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route3> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route3> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route3> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route3> extends { response: infer R } ? R : undefined>;
  };
  "get /organizations": {
    params: SchemaType<InferSchema<typeof route4> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route4> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route4> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route4> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route4> extends { response: infer R } ? R : undefined>;
  };
  "post /organizations": {
    params: SchemaType<InferSchema<typeof route5> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route5> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route5> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route5> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route5> extends { response: infer R } ? R : undefined>;
  };
  "get /organizations/:orgId": {
    params: SchemaType<InferSchema<typeof route6> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route6> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route6> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route6> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route6> extends { response: infer R } ? R : undefined>;
  };
  "get /organizations/:orgId/cloud-accounts": {
    params: SchemaType<InferSchema<typeof route7> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route7> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route7> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route7> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route7> extends { response: infer R } ? R : undefined>;
  };
  "post /organizations/:orgId/cloud-accounts": {
    params: SchemaType<InferSchema<typeof route8> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route8> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route8> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route8> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route8> extends { response: infer R } ? R : undefined>;
  };
  "get /repos": {
    params: SchemaType<InferSchema<typeof route9> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route9> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route9> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route9> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route9> extends { response: infer R } ? R : undefined>;
  };
  "post /repos": {
    params: SchemaType<InferSchema<typeof route10> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route10> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route10> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route10> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route10> extends { response: infer R } ? R : undefined>;
  };
  "get /repos/:repoId": {
    params: SchemaType<InferSchema<typeof route11> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route11> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route11> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route11> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route11> extends { response: infer R } ? R : undefined>;
  };
  "get /users/me/environment": {
    params: SchemaType<InferSchema<typeof route12> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route12> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route12> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route12> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route12> extends { response: infer R } ? R : undefined>;
  };
  "put /users/me/environment": {
    params: SchemaType<InferSchema<typeof route13> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route13> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route13> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route13> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route13> extends { response: infer R } ? R : undefined>;
  };
  "get /workspaces": {
    params: SchemaType<InferSchema<typeof route14> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route14> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route14> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route14> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route14> extends { response: infer R } ? R : undefined>;
  };
  "post /workspaces": {
    params: SchemaType<InferSchema<typeof route15> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route15> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route15> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route15> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route15> extends { response: infer R } ? R : undefined>;
  };
  "delete /workspaces/:workspaceId": {
    params: SchemaType<InferSchema<typeof route16> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route16> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route16> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route16> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route16> extends { response: infer R } ? R : undefined>;
  };
  "get /workspaces/:workspaceId": {
    params: SchemaType<InferSchema<typeof route17> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route17> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route17> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route17> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route17> extends { response: infer R } ? R : undefined>;
  };
  "post /workspaces/:workspaceId/exec": {
    params: SchemaType<InferSchema<typeof route18> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route18> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route18> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route18> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route18> extends { response: infer R } ? R : undefined>;
  };
  "post /workspaces/:workspaceId/pr": {
    params: SchemaType<InferSchema<typeof route19> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route19> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route19> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route19> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route19> extends { response: infer R } ? R : undefined>;
  };
  "post /workspaces/:workspaceId/pr/merge": {
    params: SchemaType<InferSchema<typeof route20> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route20> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route20> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route20> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route20> extends { response: infer R } ? R : undefined>;
  };
  "get /workspaces/:workspaceId/shell": {
    params: SchemaType<InferSchema<typeof route21> extends { params: infer P } ? P : undefined>;
    query: SchemaType<InferSchema<typeof route21> extends { query: infer Q } ? Q : undefined>;
    body: SchemaType<InferSchema<typeof route21> extends { body: infer B } ? B : undefined>;
    response: SchemaType<InferSchema<typeof route21> extends { responses: infer R } ? PrimarySuccessResponse<R> : InferSchema<typeof route21> extends { response: infer R } ? R : undefined>;
  };
};

export function createApiClient(options: ClientOptions): Client<AppRouteMap> {
  return createClient<AppRouteMap>(options);
}
